### ISSUE TITLE
Trying to get seeded data to show restaurants under associated wishlist in the browser.

### ISSUE THREAD

**Issue by jcngov** [adrianxadamn/pickyeater_app#17]
to: @EARnagram 
**What user story am I working on?**

AAU I want to show my wishlists that contain all the restaurants that I would like to eat at.

**What error am I getting?**

I am not getting an error, but when I seed my data, it shows that List1 contains a restaurants field, which holds one restaurant in the array.  But, when I console log wishlists in my browser, it shows that restaurants is an empty array.

**What have I already attempted in trying to fix the error?**

I looked in the mongoose documentation: 
http://mongoosejs.com/docs/subdocs.html

Under subdocs: I followed the .push method to add a subdoc, but I’m not sure why it’s not showing in the browser.

**Comment by ghost** [comment]
@jcngov Are you calling `.save()` after `.push()`?

**Comment by jcngov** [comment]
@h4w5 no I'm not I'll give it a shot right now. Thanks!

**Comment by ezRAez** [comment]
@jcngov also, have you looked in your db to see if the data was saved?

**Comment by jcngov** [comment]
double-checked in the mongo shell and realized it wasn't saving.  I added a forEach through my wishlists and called .save. IT WORKS! Thanks @h4w5 @EARnagram
